apiVersion: apps/v1
kind: Deployment
metadata:
  name: laracoffee
  namespace: laracoffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: 043309364774.dkr.ecr.us-east-1.amazonaws.com/laracoffee:17
          ports:
          - containerPort: 8000
          env:
            # Load Database Secrets
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: env-config
              mountPath: /var/www/.env
              subPath: .env
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: env-config
          configMap:
            name: laravel-env
