apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laracoffee  # Change if needed
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # Use "nlb" for Network Load Balancer or "elb" for Classic Load Balancer
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 8000  # Laravel container port
  type: LoadBalancer
