apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: 
spec:
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat
        name: tomcat
        ports:
        - containerPort: 8080
          name: tomcat-app
